### ISSUE TITLE
Redundancy in nginx-default-conf.sls?

### ISSUE THREAD

**Issue by esacteksab** [saltops/saltmine#10]
Per the docs: http://docs.saltstack.org/ref/states/requisites.html?highlight=require_in

   "The watch statement does everything the require statement does, but with a little more. "

I believe watch_in: in https://github.com/saltops/saltmine/blob/master/saltmine/states/nginx/nginx-default-conf.sls is redundant to require_in

**Comment by inthecloud247** [comment]
fixed this. thx!
