### ISSUE TITLE
File.Managed for nginx/init.sls but no source?

### ISSUE THREAD

**Issue by esacteksab** [saltops/saltmine#11]
Per the docs: http://docs.saltstack.org/ref/states/all/salt.states.file.html?highlight=file.managed#salt.states.file.managed

"source
    The source file to download to the minion, this source file can be hosted on either the salt master server, or on an http or ftp server. For files hosted on the salt file server, if the file is located on the master in the directory named spam, and is called eggs, the source string is salt://spam/eggs. If source is left blank or None, the file will be created as an empty file and the content will not be managed
   If the file is hosted on a http or ftp server then the source_hash argument is also required"

If source is empty, why are we managing it? 
If we're managing it? Where is the source? 
Why is salt creating this file? This will get created when we install nginx.

**Comment by inthecloud247** [comment]
Yeah this nginx state is unfinished and was done a whole ago. Will clean it up for the nginx file server we're building out.

**Comment by inthecloud247** [comment]
fixed the nginx setup. works fine now.
